/* store is a critical part of managing the application's state. 
It serves as a centralized place to store and manage the data for your application
The store holds the complete state tree of your application and provides methods 
to interact with and modify that state. When the state in the store is modified,
 React Redux automatically triggers component re-rendering to reflect the updated data */
import { configureStore } from '@reduxjs/toolkit';
//studentsReducer, it is the reducer generated by the studentsSlice
import studentsReducer from '../slices/studentsSlice';
import booksReducer from '../slices/booksSlice';

const store = configureStore({
    reducer: {
      students:studentsReducer,
      books:booksReducer,
  },
});

export default store;
