import React, { useState } from "react";
import axios from "axios";
import { useDispatch } from "react-redux";
import { addBook } from "../slices/booksSlice";
import { useNavigate, useParams, Link } from "react-router-dom";

const AddBook = () => {
  const navigate = useNavigate();
  const { studentId } = useParams();
  console.log(studentId);
  const [book, setBook] = useState({ name: "", author: "" });
  const dispatch = useDispatch();

  const onChangeHandler = (event)=>{
    let name = event.target.name;
    let value = event.target.value;
    setBook({[name]:value})
  };

  const handleAddBook = async () => {
    if (book.name.trim() === "" || book.author.trim() === "") {
      alert("Please fill the data correctly");
      return;
    }

    const newBook = { ...book, student_id: studentId };
    const token = `b49a4d48-3468-4889-af26-96175e3dd7a6`;
    try {
      const response = await axios.post(
        `http://localhost:8080/students/${studentId}/book`,
        newBook,
        {
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${token}`,
          },
          withCredentials: true, // Moved to the same object
        }
      );

      newBook.id = response.data.id; //we assign id bcz it is autogenerated by backend
      dispatch(addBook(newBook));
      alert("Book added Successfully");
    } catch (error) {
      console.log(error);
    }

    setBook({ name: "", author: "" });
    navigate(`/books/${studentId}`);
    // navigate(`/books/?id=${studentId}`);//another way to pass data
  };

  return (
    <div>
      <h2>Add Book for Student whose id is {studentId}</h2>
      <input
        type="text"
        placeholder="Name"
        defaultValue={book.name}
        onChange={(eventObj) =>
          setBook({ ...book, name: eventObj.target.value })
        }
      />
      <br />
      <input
        type="text"
        placeholder="Author"
        defaultValue={book.author}
        onChange={(eventObj) =>
          setBook({ ...book, author: eventObj.target.value })
        }
      />
      <br />
      <button onClick={handleAddBook} className="btn btn-success">
        Add
      </button>
      <br />
      <Link to="/students" className="btn btn-sm btn-primary">
        Back
      </Link>
    </div>
  );
};

export default AddBook;
