
import { configureStore } from '@reduxjs/toolkit';
//studentsReducer, it is the reducer generated by the studentsSlice
import studentsReducer from './slices/studentsSlice';
import booksReducer from './slices/booksSlice';

const store = configureStore({
    reducer: {
      students:studentsReducer,
      books:booksReducer,
  },
});

export default store;
